- name: Run Firewall
  hosts: localhost
  gather_facts: false
  roles:
    - delete_ssh_rule
    - add_ssh_rule
- name: Install Podman and run Nginx container
  hosts: all
  gather_facts: yes  # Replace with the name of your EC2 host or group
  remote_user: ec2-user  
  roles:
    - install_podman
